export type Lang = "zh" | "en" | "ja";

export const LINKS = {
  email: "Christianzhou77@gmail.com",
  phone: "+61 431 973 721",
  github: "https://github.com/SydneyMCDonaldbigking",
  linkedin: "https://www.linkedin.com/in/tianqi-zhou-7b81573ba",
  resume: "/Tianqi_Zhou.pdf",
  wilLive:
    "https://capstone-project-26t2-9900-w15c-cake-hec4.onrender.com",
  jobMediator:
    "https://github.com/SydneyMCDonaldbigking/ai-job-mediator-no-api",
  ugcClone: "https://github.com/SydneyMCDonaldbigking/ugc_clone",
  snsSkills: "https://github.com/SydneyMCDonaldbigking/sns_skills",
};

export const copy = {
  zh: {
    role: "AI Engineer · Automation · Applied AI",
    location: "From Chengdu to Sydney",
    nav: {
      about: "关于",
      work: "经历",
      projects: "项目",
      skills: "能力",
      contact: "联系",
    },
    heroKicker: "AI Engineer · Automation · Applied AI",
    heroName: "周天棋",
    heroTitle: "From Chengdu to Sydney.",
    heroLead: "我做能上线的 AI 系统：RAG、工作流自动化、AIGC 产线。",
    heroBody: [
      "6 年电商与品牌经验让我从用户和结果出发。现在把内容生产、运营流程和知识检索写成真正跑着的系统——不是只接一个模型 API。",
    ],
    proof: [
      "RAG systems",
      "AI workflow automation",
      "AIGC pipelines",
      "6 years in e-commerce",
    ],
    featuredLabel: "Live · WIL AI Assistant",
    featuredHref: LINKS.wilLive,
    ctaPrimary: "看我的项目",
    ctaSecondary: "联系我",
    ctaResume: "下载简历",
    sceneNight: "夜空",
    sceneSnow: "雪樱",
    scroll: "往下看",
    aboutTitle: "从品牌，到 AI",
    aboutEyebrow: "关于我",
    aboutParas: [
      "以前在成都运营独立 Lolita 女装品牌 6 年：选款、内容、电商、用户运营和团队。那段经历让我很早就习惯一件事——技术最终要解决真实问题。",
      "后来到悉尼读信息技术硕士，开始把过去靠人工完成的流程写成系统。",
      "现在主要做 AI 应用和自动化：RAG、LLM API、后端服务、AIGC 视频、RPA 和社媒工作流。",
      "我做的不是 Demo。是把一个需要人反复操作的流程拆开、重组，再让 AI 稳定接手。",
    ],
    stats: [
      { k: "6 年", v: "品牌与电商经验" },
      { k: "WAM 80", v: "UNSW 信息技术硕士" },
      { k: "3 语", v: "中文 / English / 日本語" },
      { k: "¥0.60", v: "单条 2K AIGC 视频成本" },
    ],
    cities: [
      { id: "chengdu", name: "成都", caption: "以前", image: "/media/chengdu.jpg" },
      { id: "sydney", name: "Sydney", caption: "现在", image: "/media/sydney.jpg" },
    ],
    workTitle: "我做过什么",
    workEyebrow: "经历",
    roles: [
      {
        org: "UMALL / 澳大利亚在线商超",
        title: "AI 自动化开发工程师",
        period: "2026.06 — 至今",
        place: "Sydney",
        logo: "/media/umall-logo.png",
        points: [
          "从 0 到 1 搭建社媒自动化工作流：选题、素材处理、跨语言改写、图像生成和发布，用于 Instagram / Facebook 的持续内容生产。",
          "搭建 AIGC 视频产线（参考分析、脚本拆解、分镜、图像生成、多镜头成片与后处理）。重新设计生成链路后，单条 2K 视频成本约 ¥0.60。",
          "参与需求拆解、Figma 原型、用户流程和验收。线上问题先稳定复现，再通过日志、接口和控制变量定位。",
        ],
      },
      {
        org: "产学研合作",
        title: "工业 AI 可行性验证项目",
        period: "2025.12 — 2026.02",
        place: "Remote",
        points: [
          "对接 OPC 工业设备数据，完成自动采集、清洗和预处理。",
          "基于历史运行参数做特征处理、模型训练和验证，评估现有数据对目标变量的预测能力。",
          "实验表明现有数据与特征不足以支持可靠预测，项目未进入生产部署。这段经历的价值是：知道什么时候应该停下一个机器学习项目。",
        ],
      },
      {
        org: "Little Feast Studio",
        title: "创始人 / 运营负责人",
        period: "2018.08 — 2024.08",
        place: "Chengdu",
        image: "/media/work-lolita.jpg",
        points: [
          "创立并运营独立 Lolita 女装品牌 6 年。选款、上新、内容、电商到用户运营都亲自做过，也负责团队和销售转化。",
          "长期直接面对用户反馈：用户说什么重要，他们最后怎么选择更重要。",
        ],
      },
    ],
    projectsTitle: "最近在做的东西",
    projectsEyebrow: "项目",
    featured: "精选",
    live: "Live Demo",
    code: "GitHub",
    problem: "Problem",
    built: "Built",
    result: "Result",
    projects: [
      {
        id: "wil",
        tag: "Live Demo",
        title: "WIL AI Assistant",
        problem: "学生项目经历散落，直接让 LLM 写简历容易凭空生成。",
        built: "FastAPI + Milvus RAG：先检索真实证据，再生成求职材料。",
        result: "已上线，可在线体验。",
        meta: "RAG · Milvus · FastAPI · React",
        image: "/media/shot-wil.png",
        links: [{ label: "Live Demo", href: LINKS.wilLive }],
      },
      {
        id: "ugc",
        tag: "GitHub",
        title: "UGC Clone Pipeline",
        problem: "高表现视频难复用，每次从零仿拍成本高。",
        built: "拆结构、镜头和节奏，替换商品、人物和英文口播，串成可复用产线。",
        result: "新广告内容可按流程批量生产，而不是复制原片。",
        meta: "ImageGen · MiniMax H3 · Workflow",
        image: "/media/shot-ugc.jpg",
        links: [{ label: "GitHub", href: LINKS.ugcClone }],
      },
      {
        id: "job",
        tag: "GitHub",
        title: "AI Job Mediator",
        problem: "一份简历对多份 JD，中英日材料要反复手改。",
        built: "解析 JD、匹配经历、生成三语材料。模型可替换，流程不绑死单一 API。",
        result: "自己在用的求职工作流，模型可热切换。",
        meta: "FastAPI · Chainlit · LiteLLM",
        image: "/media/shot-job.jpg",
        links: [{ label: "GitHub", href: LINKS.jobMediator }],
      },
      {
        id: "sns",
        tag: "GitHub",
        title: "Viral Social Remix",
        problem: "社媒内容每次从零做，视觉连续性和 QA 靠感觉。",
        built: "拆 IG / 小红书结构，结合商品生成轮播和竖视频，约束写进工作流。",
        result: "选题到发布可编排，用于 UMALL 官方账号持续生产。",
        meta: "AIGC · OpenRouter · FFmpeg",
        image: "/media/work-sns-ig.jpg",
        links: [{ label: "GitHub", href: LINKS.snsSkills }],
      },
      {
        id: "wechat",
        tag: "Case Study",
        title: "企业知识库客服",
        problem: "企业资料散落，客服重复回答同类问题。",
        built: "资料入库 + RAG 检索，结合桌面自动化生成自然语言回复。",
        result: "稳定运行约 3 个月，用于验证 RAG + 桌面自动化在真实业务流程中的可行性。",
        meta: "RAG · Desktop Automation",
        image: "/media/work-wechat.jpg",
      },
      {
        id: "industry",
        tag: "Case Study",
        title: "工业数据预测实验",
        problem: "产线希望用运行参数预测目标变量，但数据是否够用未知。",
        built: "OPC 采集、清洗、特征处理、模型训练与验证。",
        result: "现有数据不足以支持可靠预测，项目未进入生产。确认了：不是所有数据都值得做成预测系统。",
        meta: "OPC · Time Series · ML",
        image: "/media/work-furnace.jpg",
      },
    ],
    skillsTitle: "我能把 AI 接进真实流程",
    skillsEyebrow: "能力",
    skillGroups: [
      {
        name: "Build AI applications",
        items: ["RAG", "LLM API", "FastAPI", "Milvus", "Embeddings"],
      },
      {
        name: "Automate workflows",
        items: ["RPA", "APIs", "Queues", "Content pipelines", "AIGC"],
      },
      {
        name: "Ship & debug",
        items: ["Docker", "PostgreSQL", "Redis", "API testing", "Debugging"],
      },
    ],
    eduTitle: "Education",
    eduEyebrow: "教育",
    education: [
      {
        school: "UNSW Sydney",
        degree: "Master of Information Technology · WAM 80",
        period: "2024 — 2026",
        logo: "/media/logo-unsw.png",
      },
      {
        school: "昆明理工大学",
        degree: "Bachelor of Materials Science and Engineering",
        period: "2014 — 2018",
        logo: "/media/logo-kmust.png",
      },
    ],
    contactTitle: "AI 不应该只停在 Demo.",
    contactEyebrow: "联系",
    contactLead:
      "如果你在招 AI Engineer / Automation / Applied AI，或者手上有一个很难自动化的流程，可以找我。",
    copyEmail: "复制邮箱",
    copied: "已复制",
    footer: "周天棋 · From Chengdu to Sydney",
  },
  en: {
    role: "AI Engineer · Automation · Applied AI",
    location: "From Chengdu to Sydney",
    nav: {
      about: "About",
      work: "Work",
      projects: "Projects",
      skills: "Skills",
      contact: "Contact",
    },
    heroKicker: "AI Engineer · Automation · Applied AI",
    heroName: "Tianqi Zhou",
    heroTitle: "From Chengdu to Sydney.",
    heroLead: "I ship applied AI systems: RAG, workflow automation, AIGC pipelines.",
    heroBody: [
      "Six years in ecommerce and brand work trained me to start from users and outcomes. Now I turn content production, ops and retrieval into systems that actually stay up — not just a model API.",
    ],
    proof: [
      "RAG systems",
      "AI workflow automation",
      "AIGC pipelines",
      "6 years in e-commerce",
    ],
    featuredLabel: "Live · WIL AI Assistant",
    featuredHref: LINKS.wilLive,
    ctaPrimary: "See the work",
    ctaSecondary: "Contact",
    ctaResume: "Download resume",
    sceneNight: "Night",
    sceneSnow: "Snow",
    scroll: "Keep going",
    aboutTitle: "From brand to AI",
    aboutEyebrow: "About",
    aboutParas: [
      "I ran an independent Lolita womenswear brand in Chengdu for six years — drops, content, ecommerce, user ops and a team. That taught me early: tech only matters if it solves a real problem.",
      "Then I came to Sydney for a Master of IT and started writing the manual work into systems.",
      "I now build AI apps and automation: RAG, LLM APIs, backends, AIGC video, RPA and social workflows.",
      "Not demos. I take a process people repeat by hand, break it open, and let AI take over — stably.",
    ],
    stats: [
      { k: "6 yrs", v: "Brand & ecommerce" },
      { k: "WAM 80", v: "UNSW Master of IT" },
      { k: "3 langs", v: "ZH / English / 日本語" },
      { k: "¥0.60", v: "Cost of one 2K AIGC clip" },
    ],
    cities: [
      { id: "chengdu", name: "Chengdu", caption: "Before", image: "/media/chengdu.jpg" },
      { id: "sydney", name: "Sydney", caption: "Now", image: "/media/sydney.jpg" },
    ],
    workTitle: "What I've done",
    workEyebrow: "Work",
    roles: [
      {
        org: "UMALL / Online Asian supermarket, Australia",
        title: "AI Automation Engineer",
        period: "Jun 2026 — Present",
        place: "Sydney",
        logo: "/media/umall-logo.png",
        points: [
          "Built a social automation workflow from zero — topic, assets, rewrite, image gen, publish — for ongoing Instagram / Facebook production.",
          "Built an AIGC video pipeline (reference analysis, boards, image gen, multi-shot, post). Redesigning the chain brought one 2K clip to about ¥0.60.",
          "Also owned requirement breakdown, Figma, flows and acceptance. When production breaks, I reproduce it first, then isolate it with logs, APIs and controlled variables.",
        ],
      },
      {
        org: "Industry–university project",
        title: "Industrial AI feasibility study",
        period: "Dec 2025 — Feb 2026",
        place: "Remote",
        points: [
          "OPC ingest, cleaning and preprocessing for industrial telemetry.",
          "Feature work, training and evaluation to test whether the data could predict the target.",
          "It could not — features were insufficient, so we did not ship to production. The value was knowing when to stop an ML project.",
        ],
      },
      {
        org: "Little Feast Studio",
        title: "Founder / Head of operations",
        period: "Aug 2018 — Aug 2024",
        place: "Chengdu",
        image: "/media/work-lolita.jpg",
        points: [
          "Founded and ran an independent Lolita womenswear brand for six years. Drops, content, ecommerce, user ops — and the team through to conversion.",
          "Living in customer feedback: what people say matters. What they choose matters more.",
        ],
      },
    ],
    projectsTitle: "What I've been shipping",
    projectsEyebrow: "Projects",
    featured: "Featured",
    live: "Live Demo",
    code: "GitHub",
    problem: "Problem",
    built: "Built",
    result: "Result",
    projects: [
      {
        id: "wil",
        tag: "Live Demo",
        title: "WIL AI Assistant",
        problem: "Student work is scattered. An LLM writing a CV from scratch hallucinates.",
        built: "FastAPI + Milvus RAG: retrieve real evidence, then generate job materials.",
        result: "Live. You can try it now.",
        meta: "RAG · Milvus · FastAPI · React",
        image: "/media/shot-wil.png",
        links: [{ label: "Live Demo", href: LINKS.wilLive }],
      },
      {
        id: "ugc",
        tag: "GitHub",
        title: "UGC Clone Pipeline",
        problem: "High-performing ads are hard to reuse. Cloning from scratch is expensive.",
        built: "Extract structure, shots and rhythm; swap product, talent and English VO into a pipeline.",
        result: "New ads can be produced as a flow — not by copying the original.",
        meta: "ImageGen · MiniMax H3 · Workflow",
        image: "/media/shot-ugc.jpg",
        links: [{ label: "GitHub", href: LINKS.ugcClone }],
      },
      {
        id: "job",
        tag: "GitHub",
        title: "AI Job Mediator",
        problem: "One resume, many JDs, materials needed in ZH / EN / JA.",
        built: "Parse the JD, match experience, generate three-language packs. Models swap; the workflow does not.",
        result: "The job-search workflow I actually use. Hot-swappable models.",
        meta: "FastAPI · Chainlit · LiteLLM",
        image: "/media/shot-job.jpg",
        links: [{ label: "GitHub", href: LINKS.jobMediator }],
      },
      {
        id: "sns",
        tag: "GitHub",
        title: "Viral Social Remix",
        problem: "Social posts started from zero. Continuity and QA lived in vibes.",
        built: "Break IG / Xiaohongshu structure, restamp product, ship carousels and verticals inside a workflow.",
        result: "Topic-to-publish is orchestrated for UMALL's official accounts.",
        meta: "AIGC · OpenRouter · FFmpeg",
        image: "/media/work-sns-ig.jpg",
        links: [{ label: "GitHub", href: LINKS.snsSkills }],
      },
      {
        id: "wechat",
        tag: "Case Study",
        title: "Enterprise knowledge-base support",
        problem: "Company docs scattered. Support repeated the same answers.",
        built: "Ingest + RAG retrieval, desktop automation for natural-language replies.",
        result: "Ran about 3 months to validate RAG + desktop automation in a real ops flow.",
        meta: "RAG · Desktop Automation",
        image: "/media/work-wechat.jpg",
      },
      {
        id: "industry",
        tag: "Case Study",
        title: "Industrial forecast experiment",
        problem: "The plant wanted a forecast from operating parameters. Unclear if the data could support it.",
        built: "OPC capture, cleaning, features, training and evaluation.",
        result: "Data was not sufficient. We did not ship. Not every dataset deserves a prediction system.",
        meta: "OPC · Time Series · ML",
        image: "/media/work-furnace.jpg",
      },
    ],
    skillsTitle: "I plug AI into real workflows",
    skillsEyebrow: "Skills",
    skillGroups: [
      {
        name: "Build AI applications",
        items: ["RAG", "LLM API", "FastAPI", "Milvus", "Embeddings"],
      },
      {
        name: "Automate workflows",
        items: ["RPA", "APIs", "Queues", "Content pipelines", "AIGC"],
      },
      {
        name: "Ship & debug",
        items: ["Docker", "PostgreSQL", "Redis", "API testing", "Debugging"],
      },
    ],
    eduTitle: "Education",
    eduEyebrow: "Education",
    education: [
      {
        school: "UNSW Sydney",
        degree: "Master of Information Technology · WAM 80",
        period: "2024 — 2026",
        logo: "/media/logo-unsw.png",
      },
      {
        school: "Kunming University of Science and Technology",
        degree: "Bachelor of Materials Science and Engineering",
        period: "2014 — 2018",
        logo: "/media/logo-kmust.png",
      },
    ],
    contactTitle: "AI shouldn't stop at the demo.",
    contactEyebrow: "Contact",
    contactLead:
      "If you're hiring an AI Engineer / Automation / Applied AI, or you have a process that's hard to automate — write me.",
    copyEmail: "Copy email",
    copied: "Copied",
    footer: "Tianqi Zhou · From Chengdu to Sydney",
  },
  ja: {
    role: "AI Engineer · Automation · Applied AI",
    location: "From Chengdu to Sydney",
    nav: {
      about: "プロフィール",
      work: "経歴",
      projects: "プロジェクト",
      skills: "スキル",
      contact: "連絡",
    },
    heroKicker: "AI Engineer · Automation · Applied AI",
    heroName: "周天棋",
    heroTitle: "From Chengdu to Sydney.",
    heroLead: "本番で動く AI をつくります。RAG、ワークフロー自動化、AIGC パイプライン。",
    heroBody: [
      "6年のECとブランド経験で、ユーザーと成果から考える癖がつきました。いまはコンテンツ制作、運用、知識検索を、モデルAPIを繋いだだけではない、実際に動き続けるシステムにしています。",
    ],
    proof: [
      "RAG systems",
      "AI workflow automation",
      "AIGC pipelines",
      "6 years in e-commerce",
    ],
    featuredLabel: "Live · WIL AI Assistant",
    featuredHref: LINKS.wilLive,
    ctaPrimary: "プロジェクトを見る",
    ctaSecondary: "連絡する",
    ctaResume: "履歴書をダウンロード",
    sceneNight: "夜空",
    sceneSnow: "雪桜",
    scroll: "続きを見る",
    aboutTitle: "ブランドから、AIへ",
    aboutEyebrow: "プロフィール",
    aboutParas: [
      "成都で独立 Lolita ブランドを6年運営していました。商品、コンテンツ、EC、ユーザー運営、チームまで。技術は、本物の課題を解いてこそ意味がある、と早くから学びました。",
      "その後シドニーで情報技術修士を取り、手作業だった流れを少しずつシステムに書き直しています。",
      "いま主にやっているのは AI アプリケーションと自動化です。RAG、LLM API、バックエンド、AIGC 動画、RPA、SNS ワークフロー。",
      "デモではありません。人が何度も手を動かしていた工程を分解し、組み直し、AI に安定して渡すことです。",
    ],
    stats: [
      { k: "6年", v: "ブランドとEC" },
      { k: "WAM 80", v: "UNSW 情報技術修士" },
      { k: "3言語", v: "中国語 / English / 日本語" },
      { k: "¥0.60", v: "2K AIGC 動画1本のコスト" },
    ],
    cities: [
      { id: "chengdu", name: "成都", caption: "以前", image: "/media/chengdu.jpg" },
      { id: "sydney", name: "Sydney", caption: "いま", image: "/media/sydney.jpg" },
    ],
    workTitle: "やってきたこと",
    workEyebrow: "経歴",
    roles: [
      {
        org: "UMALL / オーストラリアのオンラインアジア食品スーパー",
        title: "AIオートメーションエンジニア",
        period: "2026.06 — 現在",
        place: "Sydney",
        logo: "/media/umall-logo.png",
        points: [
          "SNS自動化ワークフローをゼロから構築。企画、素材、多言語リライト、画像生成、投稿までを Instagram / Facebook の継続運用につなげました。",
          "AIGC 動画パイプラインを構築（参考分析、脚本分解、絵コンテ、画像生成、マルチショット、後処理）。生成チェーンを組み直し、2K 動画1本あたり約 ¥0.60 まで下げました。",
          "要件分解、Figma、ユーザーフロー、受け入れも担当。障害はまず再現し、ログ、API、変数の切り分けで特定します。",
        ],
      },
      {
        org: "産学連携",
        title: "産業AIフィージビリティ検証",
        period: "2025.12 — 2026.02",
        place: "Remote",
        points: [
          "OPC で産業機器データを取り込み、自動収集、洗浄、前処理まで実装。",
          "過去の運転パラメータで特徴量処理、学習、検証を行い、目標変数を予測できるかを評価。",
          "既存データでは信頼できる予測ができないと判断し、本番には出しませんでした。機械学習プロジェクトは、止める判断も含めて価値がある、と学びました。",
        ],
      },
      {
        org: "Little Feast Studio",
        title: "創業者 / 運営責任者",
        period: "2018.08 — 2024.08",
        place: "Chengdu",
        image: "/media/work-lolita.jpg",
        points: [
          "独立 Lolita ブランドを6年創業・運営。商品選定、入荷、コンテンツ、EC、ユーザー運営まで自分でやり、チームと売上も見ていました。",
          "ユーザーの声に毎日触れてきたので、言うことより、最後に何を選ぶかのほうが大事だ、と身についています。",
        ],
      },
    ],
    projectsTitle: "最近つくっているもの",
    projectsEyebrow: "プロジェクト",
    featured: "注目",
    live: "Live Demo",
    code: "GitHub",
    problem: "Problem",
    built: "Built",
    result: "Result",
    projects: [
      {
        id: "wil",
        tag: "Live Demo",
        title: "WIL AI Assistant",
        problem: "学生の実績が散らばっており、LLM に履歴書を書かせると幻覚が起きる。",
        built: "FastAPI + Milvus の RAG。先に証拠を検索し、そのうえで求職資料を生成。",
        result: "公開中。いま試せます。",
        meta: "RAG · Milvus · FastAPI · React",
        image: "/media/shot-wil.png",
        links: [{ label: "Live Demo", href: LINKS.wilLive }],
      },
      {
        id: "ugc",
        tag: "GitHub",
        title: "UGC Clone Pipeline",
        problem: "成果の出た動画を再利用しづらく、ゼロから真似ると高い。",
        built: "構成、カット、リズムを抽出し、商品、人物、英語ナレーションを差し替えるパイプライン。",
        result: "元映像のコピーではなく、流れとして新しい広告を量産できる。",
        meta: "ImageGen · MiniMax H3 · Workflow",
        image: "/media/shot-ugc.jpg",
        links: [{ label: "GitHub", href: LINKS.ugcClone }],
      },
      {
        id: "job",
        tag: "GitHub",
        title: "AI Job Mediator",
        problem: "履歴書は一つ、JD は複数。中・英・日の資料を手で直していた。",
        built: "JD を解析し、経歴をマッチさせ、三言語の資料を生成。モデルは差し替え可能。",
        result: "自分が実際に使っている求職ワークフロー。モデルはホットスワップ。",
        meta: "FastAPI · Chainlit · LiteLLM",
        image: "/media/shot-job.jpg",
        links: [{ label: "GitHub", href: LINKS.jobMediator }],
      },
      {
        id: "sns",
        tag: "GitHub",
        title: "Viral Social Remix",
        problem: "SNS 投稿が毎回ゼロから。見た目の連続性と QA が感覚頼み。",
        built: "IG / 小紅書の構造を分解し、商品を載せ替え、カルーセルと縦動画をワークフローに乗せる。",
        result: "企画から投稿までを編成。UMALL 公式アカウントの継続制作に使用。",
        meta: "AIGC · OpenRouter · FFmpeg",
        image: "/media/work-sns-ig.jpg",
        links: [{ label: "GitHub", href: LINKS.snsSkills }],
      },
      {
        id: "wechat",
        tag: "Case Study",
        title: "社内ナレッジベースのカスタマー対応",
        problem: "社内資料が散らばり、同じ質問への回答が繰り返されていた。",
        built: "資料の取り込み + RAG 検索、デスクトップ自動化で自然文の返信を生成。",
        result: "約3ヶ月安定稼働。実業務での RAG + デスクトップ自動化の検証に使った。",
        meta: "RAG · Desktop Automation",
        image: "/media/work-wechat.jpg",
      },
      {
        id: "industry",
        tag: "Case Study",
        title: "産業データ予測の実験",
        problem: "運転パラメータから目標変数を予測したいが、データが足りるか不明だった。",
        built: "OPC 収集、洗浄、特徴量、学習と検証。",
        result: "データでは足りず、本番には出さなかった。予測システムにする価値がないデータもある。",
        meta: "OPC · Time Series · ML",
        image: "/media/work-furnace.jpg",
      },
    ],
    skillsTitle: "AI を、本物の業務に繋ぐ",
    skillsEyebrow: "スキル",
    skillGroups: [
      {
        name: "Build AI applications",
        items: ["RAG", "LLM API", "FastAPI", "Milvus", "Embeddings"],
      },
      {
        name: "Automate workflows",
        items: ["RPA", "APIs", "Queues", "Content pipelines", "AIGC"],
      },
      {
        name: "Ship & debug",
        items: ["Docker", "PostgreSQL", "Redis", "API testing", "Debugging"],
      },
    ],
    eduTitle: "学歴",
    eduEyebrow: "教育",
    education: [
      {
        school: "UNSW Sydney",
        degree: "Master of Information Technology · WAM 80",
        period: "2024 — 2026",
        logo: "/media/logo-unsw.png",
      },
      {
        school: "昆明理工大学",
        degree: "材料科学と工学 学士",
        period: "2014 — 2018",
        logo: "/media/logo-kmust.png",
      },
    ],
    contactTitle: "AI はデモで終わらせない。",
    contactEyebrow: "連絡",
    contactLead:
      "AI Engineer / Automation / Applied AI の採用、あるいは自動化しづらい業務があれば、連絡ください。",
    copyEmail: "メールをコピー",
    copied: "コピーしました",
    footer: "周天棋 · From Chengdu to Sydney",
  },
} as const;
